### ISSUE TITLE
8563 problems - clarification

### ISSUE THREAD

**Issue by hansliss** [csoren/c128cpm#2]
None of the CP/M implementations I've tried can update the (otherwise working) VDC screen on my C128, and it's hard to find any reliable information about how the Z80 accesses the VDC. Does the original CP/M access the screen through the 8502, like it apparently does with some other I/O functions? If so, does your version do it the same way? Or do both, as I suspect, access it directly through two memory-mapped registers at  $d600/$d601?

**Comment by csoren** [comment]
No, it accesses the VDC using Z80 in/out instructions.

This is a wild guess, but maybe the IO line (which is used to signal IO, basically in/out instructions) from the Z80 to the MMU is somehow broken. CP/M doesn't use these for much, so maybe, just maybe is CP/M able to boot without them.

I would first try cleaning the Z80 and MMU sockets with contact cleaner and toothbrush (and check for corrosion while you're at it). If that doesn't help, check that the trace on the motherboard from the Z80 IO signal pin to the MMU is good using a multimeter (do this from pin to pin on the IC's when they are in the sockets). If it is, I would try swapping the Z80 for a known good one. Then try swapping the MMU for a known good one, and lastly I would try swapping the VDC for a known good one.

**Comment by hansliss** [comment]
Thank you very much!

**Comment by csoren** [comment]
Wait, if the VDC works in 8502 mode, of course it's not that one. It knows nothing about IO lines.

**Comment by csoren** [comment]
I forgot to mention checking the MMU, I've edited my answer (again!)

**Comment by hansliss** [comment]
Thanks for your comments. It helps! The /IORQ pin is actually connected to the PLA, pin 14, and that connection seems intact. There's also a 3.3 ohm pull-up on this signal, in the RP7 resistor net. I just looked at the /IORQ signal at the Z80 with the oscilloscope, and nothing useful is happening on that pin. So either the Z80 is bad, or that resistor net is. I'm closing this now, since it's not an actual issue with the CP/M project, and I have enough to go on.

**Comment by csoren** [comment]
Oh, you're right, the MMU is not involved in selecting the VDC at all.  Sorry if you found my comments patronising, it's hard to know what to include, but I'm glad if it put you on the right track.

**Comment by hansliss** [comment]
No, not at all. Nobody can possibly know what tone to set when talking to complete strangers. :)
Anyway, I've socketed the Z80 and tested with another one. No luck. I also de-soldered that resistor net, and verified that it works. So next step is to try replacing the PLA. If I can find one somewhere.

**Comment by csoren** [comment]
I thought of another thing that might be helpful - CP/M uses in/out to access the SID. If you do get keyclicks in 40 col mode, it's probably not related to the I/O line.

**Comment by hansliss** [comment]
I do get keyclicks. How annoying.

**Comment by csoren** [comment]
I guess the question then is, does it boot in 80 col mode but with a black screen so you get key clicks?

**Comment by hansliss** [comment]
I get key clicks in 80-col mode. CP/M never updates the 80-col screen so it's stuck with the original BASIC messages, up to and including "BOOTING ...". I've checked /IOCS at U3 now, and there's definitely stuff going on there. There's also a lot of activity on pin 13 on the same decoder, which is /CS8563, going to the 8563.

**Comment by csoren** [comment]
I also looked a little at U3, good to hear it's OK. This is quite the mystery. CP/M does rely on the Z80 ROM for 80 column text output somewhat, but it wouldn't be able to boot if the ROM didn't work (unless you're booting from a 1581 drive, I think - the Z80 ROM doesn't support it and it has to do its own thing), and it would probably just crash I guess. I will have to study the source code closer to get an idea of what could be wrong.

**Comment by csoren** [comment]
It's not just using the 40 col screen, is it? Can you switch to the VIC and see if something is going on there?

**Comment by hansliss** [comment]
Nope, not that simple. In 40-col mode it uses the 40-col screen, in 80-col mode it does not. Judging from my tests in VICE, most of the CP/M versions are supposed to show the loading process on both screens, but it's only ever visible on the 40-col screen. If I run it in 40-col mode, it works, of course.

Now I've run into a worse issue; I think I may have done something that caused a general failure, although I don't know what. In any case, I can't do any more troubleshooting of the CP/M issue right now, unfortunately.

**Comment by csoren** [comment]
I'm sorry to hear that. It's interesting that the loading messages don't appear on the 80 col screen, this does indicate a problem with the Z80 ROM, be it hardware or software. The ROM prints these. But again, the ROM also loads CP/M off the disk, so ...

**Comment by hansliss** [comment]
And the loading messages did appear on the 40-column screen, which suggests that the ROM must be ok. Anyway, let's hope the next C128 works better. :D

**Comment by csoren** [comment]
Well if you get another one at least you have something to swap IC's with. I have seen very strange behaviour with bad KERNAL's that kind of worked, so at least to me the Z80 ROM, the PLA and the VDC (maybe even the VDC RAM, CP/M fiddles with the refresh, but I'm not sure the ROM does) seem suspect. I'll have a look at the Z80 ROM listing later.

**Comment by hansliss** [comment]
Thanks for all your help!

**Comment by csoren** [comment]
So I haven't had time to study the ROM listing yet, but I thought of another thing that might give us a clue. 

I wrapped up CPM+.SYS in a .PRG. When loaded and run from BASIC it will continue booting from disk. The idea is to put it on a cartridge for faster booting of CP/M by avoiding the initial 32K load from disk. But of course it works fine from BASIC. Just load and run it on the 80 col screen and see what happens. It does use the same ROM routines so maybe nothing will show up. Or maybe it will.

https://github.com/csoren/cpm-loader/blob/master/cpm+.prg
